- name: install tomcat
  package:
    name: tomcat
    state: latest

- name: enable tomcat at boot
  service:
    name: tomcat
    enabled: yes

- name: create tomcat directory {{ tomcat_webapps_root }}
  file:
    path: "{{ tomcat_webapps_root }}"
    state: directory

- name: copy static index.html to {{ tomcat_webapps_root }}
  template:
    src: index.html.j2
    dest: "{{ tomcat_webapps_root }}/index.html"
    mode: 0644
  notify:
    - restart tomcat

- name: start tomcat
  service:
    name: tomcat
    state: started
